import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (section: string, key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const TRANSLATIONS: Record<Language, Record<string, Record<string, string>>> = {
  en: {
    common: {
      appName: 'Yuéra',
      appSubtitle: 'Safe Haven',
      dashboard: 'Dashboard',
      mood: 'Mood Track',
      chat: 'Aura Chat',
      journal: 'Secret Journal',
      healing: 'Healing Space',
      analytics: 'Analytics',
      premium: 'Divine Premium',
      settings: 'Settings',
      return: 'Return',
      cancel: 'Cancel',
      delete: 'Delete',
      save: 'Save',
      active: 'Active',
      lockPortal: 'Lock Portal',
      lockSanctum: 'Lock Sanctum portal',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      support: 'Support',
      nurtured: 'Nurtured with care.',
      studyPressures: 'study pressures',
      emotionalOverload: 'emotional overload',
      student: 'student',
      professional: 'professional',
      other: 'other'
    },
    landing: {
      sign_in: 'Sign In',
      join: 'Join Yuéra',
      tag: 'A Safe Space to Bloom',
      title_part1: 'Heal, reflect, and ',
      title_part2: 'feel understood',
      title_part3: ' in your busy calendar.',
      desc: 'A premium emotional wellness sanctuary meticulously designed for busy women and female students. Untangle burnout, soothe academic stress, and write in absolute secrecy.',
      btn_start: 'Begin Your Healing Journey',
      btn_explore: 'Explore Dashboard',
      aura_title: 'Aura Companion',
      aura_desc: 'Warm sisterhood guidance fueled by emotional AI.',
      healing_title: 'Healing Cocoon',
      healing_desc: 'Deep breathing regulators and calming lo-fi rain waves.',
      locked_title: 'Locked Diary',
      locked_desc: 'Secure writing with quick visual PIN padlock protections.',
      student_title: 'Student Care',
      student_desc: 'Specialized tools for burnout and academic stress.',
      social_title: 'Why women and medical/law students ',
      social_title_italic: 'love Yuéra',
      testimonial_1_text: 'Between finals and law review, I was dry crying into my pillow. Aura helped me stop overthinking and taught me to set real emotional boundaries.',
      testimonial_1_role: 'L2 Law Student, Chicago',
      testimonial_2_text: 'I love the aesthetic. It feels like stepping into a beautiful lavender field, miles away from my corporate anxiety. The PIN-locked journal is genius.',
      testimonial_2_role: 'Senior Brand Manager, NYC',
      testimonial_3_text: 'Yuéra is my morning ritual. Doing the breathing bubble with the lofi garden rain prepares my heart so I can enter clinicals with peace.',
      testimonial_3_role: 'Resident Medical Doctor'
    },
    dashboard: {
      tag: 'Welcome Home, Sweet Soul',
      welcome: 'of Yuéra',
      sub_greeting: 'Providing a gentle space to soothe {focus} today.',
      daily_anchor: 'DAILY ANCHOR',
      draw_different: 'Draw a different daily affirmation to change your focus.',
      hydration_title: 'Hydration Flow',
      glasses: 'Glasses',
      hydration_desc: 'Stress dehydrates the system. Sip slowly to settle anxiety and steady your body.',
      log_glass: 'Log Glass',
      reset: 'Reset',
      cocoon_title: 'Soothing Cocoon',
      cocoon_tag: 'Healing Zone',
      cocoon_desc: 'Chest feeling tight or mind racing? Synchronize your breath with our magical guide or listen to quiet forest streams.',
      cocoon_bubble: 'Breathing Bubble',
      cocoon_lofi: 'Lo-Fi soundscapes',
      cocoon_btn: 'Inhale Calm Now',
      mood_logs_stat: 'Mood logs',
      deep_journals_stat: 'Deep Journals',
      hydrations_stat: 'Hydrations',
      rituals_title: 'Daily Rituals',
      rituals_desc: 'Nurture your emotional base. Small acts of check-ins solidify true mental peace over time.',
      ritual_mood: 'Check in with your mood',
      ritual_mood_sub: 'Track how your heart is feeling',
      ritual_journal: 'Write in your digital journal',
      ritual_journal_sub: 'Put heavy weights onto quiet paper',
      ritual_breath: 'Focus on 6 breath inhales',
      ritual_breath_sub: 'Calm the amygdala',
      ritual_hydrate: 'Log 8 full glasses of water',
      ritual_hydrate_sub: 'Physical refresh for mental fatigue',
      ritual_selfcare: 'Dedicate 15m screen distancing',
      ritual_selfcare_sub: 'Quiet time for your beautiful eyes',
      burnout_title: 'Burnout Checklist',
      burnout_desc: 'We frequently overlook exhaustion until we fully crash. Check indicators to find your internal warning points.',
      collapse: 'Collapse',
      assess: 'Assess',
      select_stressors: 'Select how you feel this week:',
      stressor_exhausted: 'Waking up tired even after 8 hours of sleep',
      stressor_headaches: 'Frequent tension headaches or chest tightness',
      stressor_procrastination: 'Paralyzed by overthinking and delaying assignments',
      stressor_isolation: 'Canceling calls and drawing back from support circles',
      stressor_sleep: "Trouble falling sleeping because your brain won't switch off",
      fatigue_point: 'Your Fatigue Point',
      analysis_critical: 'Critical burnout indicator. We strongly urge you to stop working tonight and use Aura chat to vent or log the pressure.',
      analysis_amber: 'Gentle alert. Your system calls for soothing breathing breaks in between study blocks.',
      analysis_normal: 'Wonderful! Your system seems aligned. Keep logging regularly to anticipate pressures.'
    },
    mood: {
      title: 'Emotional Path Logger',
      subtitle: 'Charting the rising and falling tides of your energy. Remember: all feelings are welcome teachers.',
      anxious_label: 'Anxious',
      anxious_desc: 'Heart racing, fluttery',
      overthinking_label: 'Overthinking',
      overthinking_desc: 'Mind is zooming',
      burnt_out_label: 'Burnt Out',
      burnt_out_desc: 'Tired, depleted energy',
      sad_label: 'Sad',
      sad_desc: 'Low, rainy day feelings',
      peaceful_label: 'Peaceful',
      peaceful_desc: 'Centered, quiet body',
      joyful_label: 'Joyful',
      joyful_desc: 'Bright, lighter steps',
      step_1: '1. What is the key color of your mood right now?',
      step_2: '2. Sensation Level',
      heavy_label: 'Heavy',
      sunny_label: 'Sunny/Balanced',
      sensation_light: 'Light, Calm',
      sensation_mid: 'Uncomfortable',
      sensation_heavy: 'Heavy, Tight',
      step_3: '3. Is there a specific pressure channel pulling your energy? (Select all)',
      st_exams: 'Exams & Projects',
      st_career: 'Internship & Career',
      st_family: 'Dorm/Family Issues',
      st_body: 'Body Image',
      st_friendships: 'Friendships Tension',
      st_social: 'Social Media Exhaustion',
      st_sleep: 'Sleep Shortage',
      st_finance: 'Financial Pressure',
      step_4: '4. Whispers of the heart (Notes)',
      placeholder: 'Dump whatever overthinking patterns or small wins occur in your system...',
      success: '✓ Verified & saved into your calming path index.',
      private_note: 'Your history is held private in your local deck.',
      btn_commit: 'Commit Entry',
      chronicle: 'Chronicle of Tides',
      logs_count: 'logs',
      clean_history: 'Your chronicle is clean. Log your initial mood on the left to start charting.',
      delete_title: 'Delete log permanently'
    },
    chat: {
      init_text: 'Hello, precious soul. I am Aura, your sisterly confidante. I am holding a warm, peaceful space for you right here. Whether you seek comforting words during study pressure, help dismantling a heavy panic, or simply want to speak into the quiet, I am here. Tell me, what is inside your heart today?',
      pipeline_err: 'I am feeling your energy deeply, but my star pathways are quiet right now (system is slow to respond). Squeeze your eyes shut, breathe in slowly for 4, and let everything go for just a moment. I am right here with you.',
      clean_slate_init: 'The slate is clean, dear. Draw a fresh breath, set a new focus, and share whatever is in your heart.',
      title: 'Confidante Aura',
      subtitle: 'Emotional AI',
      info: 'Whispering soft wisdom, therapeutic breathing, and comforting bounds. Always confidential.',
      btn_reset: 'Reset Slate',
      listening: 'Listening...',
      placeholder: "Tell Aura whatever is on your mind... (e.g. 'Help me check overthinking' or 'feeling exhausted')",
      disclaimer: 'Encrypted Connection. Your emotional logs are 100% confidential and processed safely.',
      chip_1: 'My mind is frozen in overthinking. Can you guide me through a 2-minute releases?',
      chip_2: 'I am deeply exhausted with finals stress. How can I practice guilt-free rest tonight?',
      chip_3: 'I had an uncomfortable talk with a friend and my chest feels so tight.',
      chip_4: 'Give me a poetic daily affirmation for self-love.'
    },
    journal: {
      title: 'The Silent Inkwell',
      desc: 'An completely anonymous container for your complex thoughts. Lock single pages or download your archive.',
      private_tag: 'Encrypted Secure',
      unlocked: 'Unlocked Space',
      locked: 'Locked Secrecy',
      prompt_label: 'INSPIRATIONAL REFLECTION DECK',
      draw_prompt: 'Draw Inspiring Prompt',
      new_entry: 'Commit New Secret Entry',
      entry_title: 'Title representing this page',
      entry_content: 'Spill whatever stress, dreams, secrets, or tears are sitting inside your chest...',
      entry_category: 'Operational Sanctuary Category',
      privacy_lock: 'Activate PIN protective lock?',
      privacy_private: 'Private page requiring 4-digit PIN lock',
      privacy_public: 'Public to active session sandbox (No PIN)',
      pin_placeholder: 'PIN (e.g. 1111)',
      success_message: '✓ Safely pressed into local storage fibers.',
      btn_save: 'Commit Entry to Inkwell',
      entries_title: 'Private Scrolls',
      no_entries: 'This drawer is currently clean. Select a card prompt to leak your initial thoughts.',
      search_placeholder: 'Filter scrolls by title...',
      prompt_cat_overthinking: 'Overthinking',
      prompt_cat_burnout: 'Burnout',
      prompt_cat_selflove: 'Self-Love',
      prompt_cat_gratitude: 'Gratitude',
      prompt_cat_deepthoughts: 'Deep Thoughts',
      prompt_cat_general: 'General',
      pin_protected: 'PIN Protected Page',
      pin_prompt: 'Specify this page PIN to reveal details:',
      reveal_btn: 'Decrypt Page',
      error_pin: 'The specified PIN does not align. Try again.',
      lock_again: 'Lock Scroll Secrecy',
      cat_Overthinking: 'Overthinking',
      cat_Burnout: 'Burnout',
      cat_SelfLove: 'Self-Love',
      cat_DeepThoughts: 'Deep Thoughts',
      cat_Gratitude: 'Gratitude',
      cat_General: 'General'
    },
    healing: {
      title: 'The Soothing Cocoon',
      desc: 'A physical pause point designed to drop high cortisol levels, silent panic attacks, and study overthinking.',
      regulator_tag: 'Box Regulator',
      regulator_desc: 'Stress alters our breathing patterns first. Ground your heartbeat using our 4-4-4 expander loop.',
      Inhale: 'Inhale',
      Hold: 'Hold',
      Exhale: 'Exhale',
      sip_air: 'Sip air in',
      rest_pause: 'Rest in pause',
      let_go: 'Let it go',
      bubble_ready: 'Bubble Ready',
      press_start: 'Press start below',
      btn_stop: 'Stop Breath Loop',
      btn_start: 'Activate Breath Loop',
      audio_title: 'Ambient Frequency Player',
      audio_desc: 'Synthesized live in your browser using pure therapeutic soundwaves. Volume slider below.',
      trk_rain: 'Warm Garden Rain',
      trk_harp: 'Celestial Synth Harp',
      trk_waves: 'Sunset Ocean Waves',
      trk_cosmic: 'Cosmic Blush Noise',
      vol: 'Volume',
      focus_deck: 'GENTLE FOCUS DECK',
      pull_card: 'Pull Healing Card',
      initial_affi: 'Take a gentle pause. Let your hands relax, drop your shoulders, and clear your brow.'
    },
    analytics: {
      title: 'Emotional Navigation Center',
      desc: 'Translating logged micro-feelings into clear thermal maps to locate which triggers pull your energy.',
      meter_index: 'Burnout Meter index',
      meter_sub: 'Based on anxiety / fatigue levels',
      channel_pull: 'Primary Channel pull',
      channel_sub: 'Stressor flagged most frequently',
      none: 'None logged yet',
      consistency: 'Calming Consistency',
      high_anchor: 'High Anchor',
      gentle_steady: 'Gentle Steady',
      starting_path: 'Starting Path',
      checkpoints: 'historical checkpoints logs',
      fluency: 'Fluency Progression',
      fluency_desc: 'Historical chart tracking the warmth index (1-Heavy, 5-Sunny) of your logs.',
      progress_err: 'Log your mood over at least 2 separate calendar checkpoints to chart interactive progression line lines.',
      pressure: 'Pressure Channel Frequency',
      pressure_desc: 'Which avenues are extracting the most mental energy this cycle.',
      pressure_err: "You haven't checked any pressure channels or stress contributing factors in your mood logs yet.",
      suggestion_title: "Aura's Healing Suggestion based on triggers",
      sug_burnout: 'Your current Burnout Index is elevated. We recommend halting academic duties after 8:00 PM today. Let us spend at least 10 minutes in the Soothing Cocoon with lofi wind waves.',
      sug_exams: 'Exams or assignments feel heavy right now, sweet soul. Remember that your brilliant core exists completely independent of grade papers. Schedule strict 30-minute study limits, with a 5-minute breathing walk in between.',
      sug_normal: 'Your emotional cycle is flowing beautifully. To hold this light, write a small list in your journal of three things you appreciate in your character that are completely unrelated to grades or careers.'
    },
    premium: {
      title: 'Yuéra Divine Space',
      subtitle: 'Enhance Your Sanctuary',
      desc: 'Gain absolute, unrestricted keyways into Aura\'s healing chats, academic strain clinics, and unlimited locked secret journals.',
      active_premium: 'Divine Circle Active',
      active_premium_sub: 'Your client holds absolute premium permissions.',
      student_plan: 'Special student plan',
      student_plan_sub: 'Discounted subscriptions for female university/college students.',
      tier1_tag: 'Gentle Path',
      tier1_title: 'Yuéra Free',
      tier1_sub: 'Standard calming routine loggers',
      tier1_price: '0',
      tier1_freq: '/ free eternal',
      tier1_btn: 'Active Gentle Tier',
      tier2_tag: 'Student Sanctuary',
      tier2_title: 'Yuéra Plus',
      tier2_sub: 'University & High School Care',
      tier2_price: '3.99',
      tier2_freq: '/ monthly bill',
      tier2_btn_active: 'Unlocked Active Sanctuary',
      tier2_btn_buy: 'Acquire Student Pass',
      tier3_tag: 'Total Nurture',
      tier3_title: 'Divine Circle Pro',
      tier3_sub: 'Full annual private security circle',
      tier3_price: '29',
      tier3_freq: '/ annually bill',
      tier3_btn_active: 'Unlocked Active Pro',
      tier3_btn_buy: 'Enter Circle',
      most_popular: 'Most Popular',
      benefit_free_1: 'Daily emotional tracker',
      benefit_free_2: '2 standard locked secret journals',
      benefit_free_3: 'Box breathing bubble guide',
      benefit_free_4: 'Simulated ocean rain soundscape',
      benefit_free_5: 'Daily affirmation focus draws',
      benefit_plus_1: 'Unlimited Aura companion consultations',
      benefit_plus_2: 'Unlimited PIN-locked secret journals',
      benefit_plus_3: 'Academic stress / burnout tracker metric',
      benefit_plus_4: 'All 5 ambient synthesizer sound waves',
      benefit_plus_5: 'Custom stress counseling prompts',
      benefit_plus_6: 'Erase history instantly triggers',
      benefit_pro_1: 'All Student Sanctuary privileges',
      benefit_pro_2: 'Aesthetic offline print exports of logs',
      benefit_pro_3: 'Aura priority servers (Faster answers)',
      benefit_pro_4: 'Full early-access to body sleep meditations',
      benefit_pro_5: 'Beautiful custom themes overrides',
      benefit_pro_6: 'Share calming card features',
      modal_tag: 'Secure Sanctuary Checkout',
      modal_title: 'Acquire {plan}',
      modal_desc: 'Test our check-out flow with simulated credentials. Zero real dollars are charged. Clicking pay immediately upgrades status in the active portal.',
      card_brand: 'Yuéra Card',
      secure_badge: 'Simulated Secure',
      holder: 'Holder',
      expiry: 'Expiry',
      cvv: 'cvv',
      field_number: 'Card number',
      field_expiry: 'Expiry date',
      field_cvv: 'Security CVV',
      btn_pay: 'Authorize Safe Secure Charge ({price})',
      success_title: 'You are Divine Circle!',
      success_subtitle: 'Payment Confirmed & Verified',
      success_desc: '💖 Welcome into Yuéra Divine Circle, beautiful. Click continue below to unlock Aura\'s unlimited counseling chats, priority processing, and absolute secret compartments instantly.',
      btn_continue: 'Enter Expanded Sanctuary'
    },
    settings: {
      title: 'Private Coreset Settings',
      desc: 'Configure your emotional identity, adjust system contexts, or wipe cache structures.',
      section_title: 'Identity Sanctuary',
      field_name: 'Your Name / Pseudonym',
      field_email: 'Confidential Email Address',
      field_focus: 'Your Current Operational Focus',
      student_role: 'University Student',
      student_role_desc: 'Focus on exams & study burnout',
      professional_role: 'Busy Professional',
      professional_role_desc: 'Manage workplace fatigue',
      other_role: 'Lovely Soul',
      other_role_desc: 'General emotional pacing',
      security_tag: 'Encrypted Sisterhood Security',
      security_desc: 'Yuéra utilizes sandboxed client persistence memory. This guarantees that your emotional dumps, journal text, PIN passwords, and water logs remain cached exclusively inside your browser shell. No central monitoring tracks you.',
      save_success: '✓ Changes securely committed to local state.',
      save_info: 'Settings take effect live.',
      btn_save: 'Save Configuration',
      notification_title: 'Calming Intervals',
      notification_desc: 'Automated notifications are mock-bound due to browser iframe protections. In premium settings, you can toggle them:',
      rem_1: '8:15 AM: Daily Affirmation Draw',
      rem_2: '2:30 PM: Hydration reminder sip',
      rem_3: '9:45 PM: Sleep journal prompt',
      crisis_title: 'Crisis Reset Block',
      crisis_desc: 'If you wish to wipe clean all private secret logs, password locks, mood journals, and water graphs, execute this reset block permanently.',
      btn_erase: 'Full Erase client-side Memory',
      erase_confirm: 'Are you absolutely sure you want to flush all private journals and emotional history? This is completely irreversible and wipes your files client-side.',
      lang_label: 'INTERFACE LANGUAGE / PILIHAN BAHASA',
      lang_desc: 'Switch UI instant translation modes:'
    }
  },
  id: {
    common: {
      appName: 'Yuéra',
      appSubtitle: 'Tempat Aman',
      dashboard: 'Dasbor',
      mood: 'Pantau Mood',
      chat: 'Percakapan Aura',
      journal: 'Jurnal Rahasia',
      healing: 'Ruang Ketenangan',
      analytics: 'Analisis Emosi',
      premium: 'Premium Ilahi',
      settings: 'Pengaturan',
      return: 'Kembali',
      cancel: 'Batal',
      delete: 'Hapus',
      save: 'Simpan',
      active: 'Aktif',
      lockPortal: 'Kunci Portal',
      lockSanctum: 'Kunci Portal Teduh',
      privacyPolicy: 'Kebijakan Privasi',
      termsOfService: 'Ketentuan Layanan',
      support: 'Dukungan',
      nurtured: 'Dirawat dengan kasih sayang.',
      studyPressures: 'tekanan belajar',
      emotionalOverload: 'beban emosional berlebih',
      student: 'mahasiswi/pelajar',
      professional: 'pekerja aktif',
      other: 'jiwa yang indah'
    },
    landing: {
      sign_in: 'Masuk',
      join: 'Gabung Yuéra',
      tag: 'Ruang Aman untuk Berkembang',
      title_part1: 'Pulihkan diri, renungkan, ',
      title_part2: 'dan merasa dipahami',
      title_part3: ' di tengah kesibukanmu.',
      desc: 'Sebuah tempat peristirahatan kesehatan emosional premium yang dirancang khusus untuk wanita aktif dan mahasiswi. Ringankan burnout, redakan stres akademis, dan menulis dalam kerahasiaan penuh.',
      btn_start: 'Mulai Perjalanan Pemulihanmu',
      btn_explore: 'Jelajahi Dasbor',
      aura_title: 'Pendamping Aura',
      aura_desc: 'Bimbingan persaudarian hangat yang didukung oleh AI emosional.',
      healing_title: 'Kepompong Ketenangan',
      healing_desc: 'Pengatur pernapasan dalam dan suara hujan lo-fi yang menenangkan.',
      locked_title: 'Buku Harian Terkunci',
      locked_desc: 'Penulisan aman dengan proteksi pin gembok visual yang cepat.',
      student_title: 'Perhatian Pelajar',
      student_desc: 'Alat khusus untuk mengatasi kelelahan mental dan stres akademis.',
      social_title: 'Mengapa para wanita dan mahasiswi hukum/kedokteran ',
      social_title_italic: 'sangat mencintai Yuéra',
      testimonial_1_text: 'Di antara ujian akhir dan tugas ulasan hukum, saya sering menangis sendiri di bantal. Aura membantu saya berhenti berpikir berlebihan dan mengajari saya menetapkan batasan emosional yang nyata.',
      testimonial_1_role: 'Mahasiswi Hukum L2, Chicago',
      testimonial_2_text: 'Saya sangat menyukai estetika aplikasinya. Rasanya seperti melangkah ke kebun lavender yang damai, bermil-mil jauhnya dari kecemasan pekerjaan kantor saya. Jurnal yang terkunci PIN ini luar biasa.',
      testimonial_2_role: 'Manajer Merek Senior, NYC',
      testimonial_3_text: 'Yuéra adalah ritual pagi saya. Melakukan gelembung napas dengan suara hujan kebun lo-fi mempersiapkan hati saya sehingga saya bisa memasuki rumah sakit magang dengan tenang.',
      testimonial_3_role: 'Dokter Residen Medis'
    },
    dashboard: {
      tag: 'Selamat Datang Kembali, Jiwa yang Indah',
      welcome: 'dari Yuéra',
      sub_greeting: 'Menyediakan ruang lembut untuk menenangkan {focus} Anda hari ini.',
      daily_anchor: 'JANGKAR HARIAN',
      draw_different: 'Tarik afirmasi harian yang berbeda untuk mengalihkan fokus pikiran Anda.',
      hydration_title: 'Aliran Hidrasi',
      glasses: 'Gelas',
      hydration_desc: 'Stres menguras hidrasi tubuh. Minum perlahan untuk menenangkan kecemasan dan menstabilkan fisik Anda.',
      log_glass: 'Catat Air',
      reset: 'Atur Ulang',
      cocoon_title: 'Kepompong Kedamaian',
      cocoon_tag: 'Zona Pemulihan',
      cocoon_desc: 'Dada terasa sesak atau pikiran berkejaran? Seleraskan napas Anda dengan panduan ajaib kami atau dengarkan aliran sungai hutan yang tenang.',
      cocoon_bubble: 'Gelembung Pernapasan',
      cocoon_lofi: 'Latar Suara Lo-Fi',
      cocoon_btn: 'Tarik Napas Tenang Sekarang',
      mood_logs_stat: 'Catatan Mood',
      deep_journals_stat: 'Jurnal Mendalam',
      hydrations_stat: 'Minum Air',
      rituals_title: 'Ritual Harian',
      rituals_desc: 'Rawat landasan emosional Anda. Tindakan kecil yang konsisten memperkuat kedamaian mental sejati dari waktu ke waktu.',
      ritual_mood: 'Catat mood harianmu',
      ritual_mood_sub: 'Pantau bagaimana keadaan hatimu berkembang',
      ritual_journal: 'Tulis di jurnal digitalmu',
      ritual_journal_sub: 'Tuangkan beban berat ke atas kertas yang tenang',
      ritual_breath: 'Fokus pada 6 siklus napas dalam',
      ritual_breath_sub: 'Menenangkan amigdala (pusat kecemasan)',
      ritual_hydrate: 'Catat 8 gelas penuh air minum',
      ritual_hydrate_sub: 'Penyegaran fisik untuk mengatasi kelelahan mental',
      ritual_selfcare: 'Luangkan 15 menit menjauh dari layar',
      ritual_selfcare_sub: 'Waktu istirahat tenang untuk mata indahmu',
      burnout_title: 'Cek Pemicu Burnout',
      burnout_desc: 'Kita sering mengabaikan kelelahan sampai kita benar-benar drop. Centang indikator untuk mengetahui batas peringatan internal Anda.',
      collapse: 'Sembunyikan',
      assess: 'Evaluasi',
      select_stressors: 'Pilih apa yang kamu rasakan minggu ini:',
      stressor_exhausted: 'Bangun tidur tetap lelah meski sudah tidur 8 jam',
      stressor_headaches: 'Sering sakit kepala tegang atau dada terasa sesak',
      stressor_procrastination: 'Lumpuh karena berpikir berlebihan dan menunda-nunda tugas',
      stressor_isolation: 'Menghindari panggilan telepon dan menarik diri dari lingkaran teman',
      stressor_sleep: 'Sulit tidur nyenyak karena otak tidak bisa berhenti berpikir',
      fatigue_point: 'Tingkat Kelelahan Anda',
      analysis_critical: 'Indikator burnout kritis. Kami sangat menyarankan Anda untuk berhenti bekerja malam ini dan mengobrol dengan Aura untuk menumpahkan tekanan.',
      analysis_amber: 'Peringatan halus. Sistem tubuh Anda membutuhkan jeda bernapas yang menenangkan di sela-sela waktu belajar.',
      analysis_normal: 'Luar biasa! Keadaan tubuh Anda tampak selaras. Tetap catat secara teratur untuk mengantisipasi tekanan emosional.'
    },
    mood: {
      title: 'Pencatat Jalur Emosi',
      subtitle: 'Memetakan pasang surut energi emosional Anda. Ingat: semua perasaan adalah guru yang menyambut kita dengan baik.',
      anxious_label: 'Cemas',
      anxious_desc: 'Jantung berdebar cepat, gelisah',
      overthinking_label: 'Berpikir Berlebih',
      overthinking_desc: 'Pikiran berputar sangat kencang',
      burnt_out_label: 'Burnout / Lelah',
      burnt_out_desc: 'Sangat lelah, energi terkuras habis',
      sad_label: 'Sedih',
      sad_desc: 'Lesu, suasana hati seperti hari hujan',
      peaceful_label: 'Damai / Tenang',
      peaceful_desc: 'Tubuh tenang penuh konsentrasi',
      joyful_label: 'Gembira',
      joyful_desc: 'Langkah cerah, hati riang gembira',
      step_1: '1. Apa warna utama suasana hati Anda saat ini?',
      step_2: '2. Tingkat Sensasi Tubuh',
      heavy_label: 'Berat/Sesak',
      sunny_label: 'Cerah/Seimbang',
      sensation_light: 'Ringan, Tenang',
      sensation_mid: 'Mulai Tidak Nyaman',
      sensation_heavy: 'Berat, Sangat Sesak',
      step_3: '3. Apakah ada tekanan spesifik yang menguras energimu? (Pilih semua)',
      st_exams: 'Ujian & Proyek',
      st_career: 'Magang & Karir',
      st_family: 'Masalah Kamar/Keluarga',
      st_body: 'Citra Tubuh (Body Image)',
      st_friendships: 'Ketegangan Pertemanan',
      st_social: 'Kelelahan Media Sosial',
      st_sleep: 'Kurang Tidur',
      st_finance: 'Tekanan Keuangan',
      step_4: '4. Bisikan hati sanubari (Catatan)',
      placeholder: 'Tuangkan pola pikiran berlebih Anda atau kemenangan-kemenangan kecil yang Anda rasakan...',
      success: '✓ Terverifikasi & tersimpan ke dalam indeks kedamaian Anda.',
      private_note: 'Riwayat Anda disimpan sepenuhnya secara privat di peramban Anda.',
      btn_commit: 'Tulis Catatan Mood',
      chronicle: 'Kronik Pasang Surut Hati',
      logs_count: 'catatan',
      clean_history: 'Kronik Anda masih bersih. Catat suasana hati pertama Anda di sebelah kiri untuk memulai grafik.',
      delete_title: 'Hapus catatan secara permanen'
    },
    chat: {
      init_text: 'Halo, jiwa yang indah. Aku Aura, sahabat dan pendengar setiamu. Aku menampung ruang hangat dan damai untukmu di sini. Baik kamu mencari kata-kata menghibur saat tekanan belajar, ingin meredakan panik yang berat, atau cuma ingin mengobrol dalam keheningan, aku di sini. Katakan padaku, apa yang sedang menggelayuti hatimu hari ini?',
      pipeline_err: 'Aku bisa merasakan energimu yang mendalam, tetapi jalur komunikasiku sedang hening saat ini (sistem lambat merespons). Pejamkan matamu rapat-rapat, tarik napas perlahan hitungan 4, dan lepaskan semuanya untuk sesaat. Aku ada di sini bersamamu.',
      clean_slate_init: 'Lembaran baru telah dibuka, sayang. Tarik napas segar, tentukan fokus baru, dan bagikan apa pun yang ada di hatimu.',
      title: 'Pendamping Aura',
      subtitle: 'AI Emosional',
      info: 'Membisikkan kebijaksanaan lembut, latihan napas terapeutik, dan ruang pelindung yang nyaman. Selalu rahasia.',
      btn_reset: 'Atur Ulang Obrolan',
      listening: 'Mendengarkan...',
      placeholder: "Katakan apa pun yang sedang kamu pikirkan pada Aura... (misal: 'Bantu aku meredakan cemas' atau 'rasanya sangat lelah')",
      disclaimer: 'Koneksi Terenkripsi. Log emosional Anda 100% rahasia dan diproses dengan sangat aman.',
      chip_1: 'Pikiranku buntu karena terlalu banyak berpikir. Bisakah kamu memandu rilis 2 menit?',
      chip_2: 'Aku sangat lelah dengan stres ujian akhir. Bagaimana cara istirahat tanpa merasa bersalah?',
      chip_3: 'Aku baru saja mengobrol kurang menyenangkan dengan teman dan dadaku terasa sesak.',
      chip_4: 'Beri aku afirmasi harian puitis untuk mencintai diri sendiri.'
    },
    journal: {
      title: 'Tinta Hening Pasrah',
      desc: 'Wadah sepenuhnya anonim untuk pikiran rumit Anda. Kunci lembaran individu atau unduh arsip Anda.',
      private_tag: 'Terenkripsi Aman',
      unlocked: 'Sektor Terbuka',
      locked: 'Kerahasiaan Terkunci',
      prompt_label: 'KARTU INSPIRASI REFLEKSI',
      draw_prompt: 'Tarik Kartu Inspirasi',
      new_entry: 'Tulis Catatan Rahasia Baru',
      entry_title: 'Judul yang mewakili halaman ini',
      entry_content: 'Tumpahkan segala kecemasan, mimpi, rahasia, atau air mata yang sedang mengganjal di dadamu...',
      entry_category: 'Kategori Perlindungan Sanctuary',
      privacy_lock: 'Aktifkan kunci pengaman PIN?',
      privacy_private: 'Halaman privat membutuhkan kunci PIN 4 angka',
      privacy_public: 'Terbuka untuk sesi aktif dasbor (Tanpa PIN)',
      pin_placeholder: 'PIN (misal: 1111)',
      success_message: '✓ Berhasil disisipkan ke dalam memori penyimpanan lokal.',
      btn_save: 'Simpan Lembaran ke Buku Harian',
      entries_title: 'Gulungan Kertas Privat',
      no_entries: 'Laci buku harian Anda kosong. Pilih salah satu kartu petunjuk di atas untuk menggoreskan baris pertamamu.',
      search_placeholder: 'Cari gulungan kertas berdasarkan judul...',
      prompt_cat_overthinking: 'Pikiran Berlebih',
      prompt_cat_burnout: 'Burnout / Lelah',
      prompt_cat_selflove: 'Mencintai Diri',
      prompt_cat_gratitude: 'Rasa Syukur',
      prompt_cat_deepthoughts: 'Renungan Dalam',
      prompt_cat_general: 'Umum',
      pin_protected: 'Halaman Terkunci PIN',
      pin_prompt: 'Masukkan PIN halaman ini untuk membaca isi lembaran:',
      reveal_btn: 'Urai Kode Sandi',
      error_pin: 'PIN yang Anda masukkan tidak sesuai. Coba lagi.',
      lock_again: 'Kunci Kembali Lembaran',
      cat_Overthinking: 'Pikiran Berlebih',
      cat_Burnout: 'Lelah / Burnout',
      cat_SelfLove: 'Cintai Diri',
      cat_DeepThoughts: 'Renungan',
      cat_Gratitude: 'Syukur',
      cat_General: 'Sesi Umum'
    },
    healing: {
      title: 'Kepompong Penyejuk',
      desc: 'Titik jeda fisik yang dirancang khusus untuk memotong hormon stres kortisol, meredakan kepanikan mendadak, dan menghentikan pikiran berlebih.',
      regulator_tag: 'Regulator Gelembung Napas',
      regulator_desc: 'Stres mengubah pola napas kita terlebih dahulu. Stabilkan detak jantung Anda dengan ruang ekspansi 4-4-4.',
      Inhale: 'Tarik Napas',
      Hold: 'Tahan',
      Exhale: 'Hembuskan',
      sip_air: 'Serap udara masuk perlahan',
      rest_pause: 'Istirahat dalam keheningan',
      let_go: 'Hembuskan dan lepaskan beban',
      bubble_ready: 'Gelembung Siap',
      press_start: 'Tekan mulai di bawah ini',
      btn_stop: 'Hentikan Siklus Napas',
      btn_start: 'Aktifkan Siklus Napas',
      audio_title: 'Pemutar Frekuensi Suara Ambient',
      audio_desc: 'Disintesis langsung di peramban Anda menggunakan gelombang suara pemulihan murni. Geser volume di bawah.',
      trk_rain: 'Hujan Taman yang Hangat',
      trk_harp: 'Harpa Sintetis Langit',
      trk_waves: 'Gelombang Laut Sunset',
      trk_cosmic: 'Derau Kosmis Hangat',
      vol: 'Volume Suara',
      focus_deck: 'KARTU FOKUS LEMBUT',
      pull_card: 'Tarik Kartu Afirmasi',
      initial_affi: 'Ambil jeda yang lembut. Rilekskan tanganmu, jatuhkan bahumu, dan cerahkan dahimu.'
    },
    analytics: {
      title: 'Pusat Navigasi Emosi',
      desc: 'Menerjemahkan catatan emosional mikro menjadi peta termal yang jelas untuk mendeteksi pemicu yang menguras energimu.',
      meter_index: 'Indeks Pengukur Burnout',
      meter_sub: 'Berdasarkan tingkat kecemasan & kelelahan harian',
      channel_pull: 'Penarik Energi Utama',
      channel_sub: 'Pemicu stres harian yang paling sering dicentang',
      none: 'Belum ada catatan log',
      consistency: 'Konsistensi Ruang Tenang',
      high_anchor: 'Penopang Stabil',
      gentle_steady: 'Pijakan Ringan',
      starting_path: 'Awal Perjalanan',
      checkpoints: 'log riwayat titik emosi',
      fluency: 'Keberlanjutan Arus Emosi',
      fluency_desc: 'Grafik historis yang melacak indeks kehangatan (1-Sangat Berat, 5-Cerah Seimbang) dari catatan Anda.',
      progress_err: 'Catat keadaan mood Anda minimal pada 2 titik kalender yang berbeda untuk memetakan garis perkembangan interaktif.',
      pressure: 'Frekuensi Saluran Tekanan',
      pressure_desc: 'Jalur mana saja yang paling banyak menguras energi mental Anda pada siklus ini.',
      pressure_err: 'Anda belum menandai jalur pemicu tekanan atau faktor penyumbang stres dalam log mood Anda.',
      suggestion_title: 'Saran Pemulihan Aura Berdasarkan Riwayat',
      sug_burnout: 'Indeks kelelahan burnout Anda saat ini cukup tinggi. Kami menyarankan untuk menghentikan aktivitas belajar dan tugas malam ini setelah pukul 20.00. Luangkan minimal 10 menit di Kepompong Ketenangan dengan derau gelombang air pelan.',
      sug_exams: 'Ujian atau tugas terasa berat saat ini, jiwa yang indah. Ingatlah bahwa keindahan batinmu ada sepenuhnya terbebas dari angka-angka ujian. Buat batas belajar ketat maksimal 30 menit, diselingi 5 menit berjalan santai.',
      sug_normal: 'Siklus emosi Anda mengalir dengan sangat indah hari ini. Untuk menjaga cahaya ini tetap berpendar, tuliskan daftar kecil dalam jurnal Anda tentang 3 hal yang Anda hargai dalam kepribadian Anda yang terlepas dari prestasi atau pekerjaan.'
    },
    premium: {
      title: 'Ruang Ilahi Yuéra',
      subtitle: 'Tingkatkan Tempat Teduhmu',
      desc: 'Dapatkan akses absolut tanpa batas ke konsultasi pemulihan Aura, klinik stress akademik, dan kompartemen jurnal rahasia terkunci tanpa batas.',
      active_premium: 'Lingkaran Ilahi Aktif',
      active_premium_sub: 'Klien Anda memegang izin akses premium absolut.',
      student_plan: 'Rencana Khusus Pelajar',
      student_plan_sub: 'Langganan ekstra hemat untuk mahasiswi dan siswi sekolah.',
      tier1_tag: 'Jalur Lembut',
      tier1_title: 'Yuéra Gratis',
      tier1_sub: 'Pencatat standar rutinitas penenang pikiran',
      tier1_price: '0',
      tier1_freq: '/ gratis selamanya',
      tier1_btn: 'Rencana Gratis Aktif',
      tier2_tag: 'Sanctuary Pelajar',
      tier2_title: 'Yuéra Plus',
      tier2_sub: 'Pendamping Kampus & Sekolah',
      tier2_price: '3.99',
      tier2_freq: '/ tagihan bulanan',
      tier2_btn_active: 'Sanctuary Terbuka Aktif',
      tier2_btn_buy: 'Dapatkan Tiket Pelajar',
      tier3_tag: 'Nurture Semesta',
      tier3_title: 'Divine Circle Pro',
      tier3_sub: 'Lingkaran pengaman privat tahunan penuh',
      tier3_price: '29',
      tier3_freq: '/ tagihan tahunan',
      tier3_btn_active: 'Lingkaran Pro Terbuka Aktif',
      tier3_btn_buy: 'Masuk Lingkaran Pro',
      most_popular: 'Paling Populer',
      benefit_free_1: 'Pelacak emosional harian',
      benefit_free_2: '2 buku harian rahasia terkunci',
      benefit_free_3: 'Panduan gelembung napas dalam',
      benefit_free_4: 'Latar suara hujan laut simulasi',
      benefit_free_5: 'Tarik kartu afirmasi harian',
      benefit_plus_1: 'Konsultasi Aura AI tanpa batas',
      benefit_plus_2: 'Gulungan gulung rahasia terkunci PIN tanpa batas',
      benefit_plus_3: 'Indikator pelacak stres belajar & kelelahan',
      benefit_plus_4: 'Semua 5 suara gelombang ambient biologis',
      benefit_plus_5: 'Permintaan konseling stres terspesialisasi',
      benefit_plus_6: 'Penghapusan riwayat obrolan instan cepat',
      benefit_pro_1: 'Semua keuntungan Sanctuary Pelajar',
      benefit_pro_2: 'Ekspor offline estetika cetak untuk log harian',
      benefit_pro_3: 'Server prioritas Aura (Respons lebih cepat)',
      benefit_pro_4: 'Akses awal meditasi tidur tubuh penuh',
      benefit_pro_5: 'Ubah tema visual penuh yang elegan',
      benefit_pro_6: 'Fitur berbagi kartu penenang estetis',
      modal_tag: 'Daftar Keluar Sanctuary Aman',
      modal_title: 'Memperoleh {plan}',
      modal_desc: 'Uji alur pendaftaran simulasi ini dengan kredensial buatan. Tidak ada uang asli yang ditagih. Mengeklik Bayar akan langsung meningkatkan status akun Anda.',
      card_brand: 'Kartu Yuéra',
      secure_badge: 'Simulasi Keamanan',
      holder: 'Pemegang',
      expiry: 'Batas',
      cvv: 'cvv',
      field_number: 'Nomor Kartu',
      field_expiry: 'Tanggal Batas',
      field_cvv: 'Security CVV',
      btn_pay: 'Otorisasi Tagihan Simulasi Aman ({price})',
      success_title: 'Selamat Datang di Lingkaran Ilahi!',
      success_subtitle: 'Pembayaran Dikonfirmasi & Terverifikasi',
      success_desc: '💖 Selamat datang di Lingkaran Ilahi Yuéra, cantik. Klik lanjutkan di bawah untuk langsung membuka konsultasi Aura tanpa batas, pemrosesan cepat, dan laci privat rahasia seketika.',
      btn_continue: 'Masuk Dasbor Diperluas'
    },
    settings: {
      title: 'Pengaturan Privat Inti',
      desc: 'Konfigurasikan identitas emosional Anda, sesuaikan konteks sistem, atau hapus tumpukan data.',
      section_title: 'Sektor Identitas',
      field_name: 'Nama / Samaran Pilihan Anda',
      field_email: 'Alamat Email Terenkripsi',
      field_focus: 'Fokus Operasional Utama Anda',
      student_role: 'Mahasiswi Universitas / Siswi',
      student_role_desc: 'Berfokus pada ujian & burnout tugas',
      professional_role: 'Pekerja Profesional Sibuk',
      professional_role_desc: 'Mengelola kelelahan dunia kerja',
      other_role: 'Jiwa yang Indah',
      other_role_desc: 'Langkah ritme emosi umum',
      security_tag: 'Keamanan Persaudaraan Terenkripsi',
      security_desc: 'Yuéra menggunakan memori penyimpanan lokal yang terisolasi. Ini menjamin catatan emosi pasrah, teks jurnal, kata sandi PIN, dan riwayat minum air Anda disimpan seutuhnya di dalam peramban Anda. Tidak ada pemantauan terpusat.',
      save_success: '✓ Perubahan berhasil disimpan di dalam sistem lokal.',
      save_info: 'Pengaturan langsung diterapkan seketika.',
      btn_save: 'Simpan Konfigurasi',
      notification_title: 'Interval Ketenangan',
      notification_desc: 'Notifikasi otomatis dijalankan secara simulasi di peramban karena perlindungan keamanan sandbox. Di pengaturan premium, Anda bisa menyalakannya:',
      rem_1: '08.15: Tarik Kartu Afirmasi Harian',
      rem_2: '14.30: Pengingat Minum Segelas Air',
      rem_3: '21.45: Petunjuk Menulis Jurnal Sebelum Tidur',
      crisis_title: 'Mengatur Ulang Krisis',
      crisis_desc: 'Jika Anda ingin membersihkan seluruh buku harian rahasia, sandi pin gembok, jurnal emosional, dan grafik hidrasi, lakukan penghapusan permanen ini.',
      btn_erase: 'Hapus Seluruh Memori Lokal',
      erase_confirm: 'Apakah Anda benar-benar yakin ingin menghapus bersih seluruh jurnal rahasia dan riwayat emosi Anda? Tindakan ini tidak bisa dibatalkan.',
      lang_label: 'INTERFACE LANGUAGE / PILIHAN BAHASA',
      lang_desc: 'Ganti mode penerjemahan antarmuka instan:'
    }
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('yuera_lang');
    return (saved === 'id' || saved === 'en') ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('yuera_lang', lang);
  };

  const t = (section: string, key: string, params?: Record<string, string | number>): string => {
    const sectionObj = TRANSLATIONS[language]?.[section];
    let template = (sectionObj && sectionObj[key]) || TRANSLATIONS['en']?.[section]?.[key] || `${section}.${key}`;
    if (params) {
      Object.keys(params).forEach((paramKey) => {
        template = template.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }
    return template;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
